### ISSUE TITLE
How do I parse back a roundtrip-json file to nbt file?

### ISSUE THREAD

**Issue by LoSunny** [unascribed/unbted#1]
As titled

**Comment by unascribed** [comment]
Sorry, I missed this somehow.

I intend to add a limited scripting system to unbted, which would include a `-c` parameter that runs a command.

When I had to do this recently, this was how I did it:

```bash
echo -e 'save -Nf -c=gzip --big-endian signs.schem\nexit\n' | java -jar ~/unbted/build/libs/unbted-1.1.jar --verbose foo.json
```

Replace "signs.schem" with the filename you wish to save to, and "foo.json" with your input unbted JSON.

**Comment by unascribed** [comment]
In 1.2, this is now done like so:

```
unbted -N -c=gzip input.json output.dat
```
